# Phần 1: Ôn tập 2D list


## Bài tập 1: Tính tổng đường chéo chính
Viết một chương trình Python để tính tổng các phần tử trên đường chéo chính của một ma trận vuông (mảng hai chiều) đã cho. Đường chéo chính là dãy các phần tử từ góc trên bên trái đến góc dưới bên phải của ma trận. Ví dụ, với ma trận sau đây:
```
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
```
Tổng của các phần tử trên đường chéo chính là 1 + 5 + 9 = 15.

Gợi ý:

Sử dụng vòng lặp để duyệt qua các hàng và cột tương ứng trên đường chéo chính.
Sử dụng chỉ số hàng và chỉ số cột giống nhau để truy cập các phần tử trên đường chéo chính.


```mermaid
graph TB
  A[Start]
  B{Check if matrix is square}
  C[Calculate sum of main diagonal]
  D[Return sum]
  E[End]
  F[Throw ValueError]
  
  A --> B
  B -- Yes --> C
  C --> D
  D --> E
  B -- No --> F


```

Các bước thực hiện:

* Kiểm tra xem ma trận có phải là ma trận vuông hay không bằng cách so sánh số hàng (len(matrix)) với số cột của ma trận đầu tiên (len(matrix[0])). Nếu không bằng nhau, hàm sẽ ném một ValueError với thông báo "Ma trận không phải là ma trận vuông."

* Khởi tạo biến diagonal_sum với giá trị ban đầu là 0.

* Sử dụng một vòng lặp for để duyệt qua các hàng của ma trận theo chỉ số i.

* Tại mỗi vòng lặp, thêm giá trị của phần tử trên đường chéo chính (matrix[i][i]) vào diagonal_sum.

* Trả về tổng các phần tử trên đường chéo chính (diagonal_sum).

Sau đó, hàm sum_main_diagonal được gọi để tính tổng các phần tử trên đường chéo chính của ma trận matrix đã được định nghĩa trước đó. Kết quả được in ra màn hình

In [3]:
def sum_main_diagonal(matrix):
    # Kiểm tra xem ma trận có phải là ma trận vuông hay không
    if len(matrix) != len(matrix[0]):
        raise ValueError("Ma trận không phải là ma trận vuông.")

    diagonal_sum = 0
    # Tính tổng các phần tử trên đường chéo chính của ma trận
    for i in range(len(matrix)):
        diagonal_sum += matrix[i][i]

    return diagonal_sum

# Kiểm tra
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print(sum_main_diagonal(matrix))  # Output: 15


15


## Bài tập 2: Sắp xếp theo tổng hàng
Viết một chương trình Python để sắp xếp một ma trận (mảng hai chiều) đã cho theo tổng của các phần tử trong mỗi hàng. Tổng của một hàng được tính bằng cách cộng tất cả các phần tử trong hàng đó. Sau khi sắp xếp, các hàng có tổng nhỏ nhất sẽ xuất hiện đầu tiên trong ma trận.

Ví dụ:
```
matrix = [
    [4, 2, 7],
    [1, 5, 6],
    [3, 8, 2]
]
```
Sau khi sắp xếp, ma trận trở thành:
```
matrix = [
    [1, 5, 6],
    [3, 8, 2],
    [4, 2, 7]
]
```

Gợi ý:
Tạo một danh sách các cặp (tổng hàng, hàng) để lưu trữ tổng của mỗi hàng và hàng tương ứng.
Sử dụng hàm sorted() trong Python để sắp xếp danh sách theo tổng hàng.
Lặp qua các cặp đã sắp xếp để tạo lại ma trận ban đầu theo thứ tự đã sắp xếp.

```mermaid
graph TB
  A[Start]
  B[Calculate row sums and pair with corresponding row]
  C[Sort rows based on sums]
  D[Extract sorted rows from pairs]
  E[Return sorted matrix]
  F[End]

  A --> B
  B --> C
  C --> D
  D --> E
  E --> F

```

Cách hoạt động của hàm là:

* Tạo một danh sách gồm các cặp (tổng hàng, hàng) bằng cách tính tổng của mỗi hàng trong ma trận.

* Sắp xếp danh sách các cặp (tổng hàng, hàng) theo tổng hàng, sử dụng hàm sorted và truyền lambda function key=lambda x: x[0] để sắp xếp theo phần tử đầu tiên của từng cặp (tổng hàng).

* Tạo một ma trận mới từ các hàng đã được sắp xếp, bằng cách lấy phần thứ hai của mỗi cặp (hàng) trong danh sách đã sắp xếp.

* Trả về ma trận đã sắp xếp.

Sau đó, hàm sort_by_row_sum được gọi để sắp xếp ma trận matrix đã được định nghĩa trước đó. Kết quả được lưu vào biến sorted_matrix, và mỗi hàng của ma trận đã sắp xếp được in ra dưới dạng các dòng riêng biệt.

In [2]:
def sort_by_row_sum(matrix):
    # Tính tổng của mỗi hàng trong ma trận và lưu vào một danh sách gồm các cặp (tổng hàng, hàng)
    row_sums = [(sum(row), row) for row in matrix]
    
    # Sắp xếp danh sách các cặp (tổng hàng, hàng) theo tổng hàng
    sorted_rows = sorted(row_sums, key=lambda x: x[0])
    print(sorted_rows)
    
    # Tạo một ma trận mới với các hàng đã được sắp xếp theo tổng hàng
    sorted_matrix = [row for _, row in sorted_rows]
    
    return sorted_matrix

# Kiểm tra
matrix = [
    [4, 2, 7],
    [1, 5, 6],
    [3, 8, 2]
]

# Gọi hàm sort_by_row_sum để sắp xếp ma trận theo tổng hàng
sorted_matrix = sort_by_row_sum(matrix)

# In ra từng hàng trong ma trận đã sắp xếp
for row in sorted_matrix:
    print(row)


[(12, [1, 5, 6]), (13, [4, 2, 7]), (13, [3, 8, 2])]
[1, 5, 6]
[4, 2, 7]
[3, 8, 2]


Cách 2:
* Sử dụng hàm sorted để sắp xếp các hàng trong ma trận matrix.

* Truyền một lambda function key=lambda row: sum(row) vào tham số key của hàm sorted, để sắp xếp các hàng dựa trên tổng của từng hàng. Lambda function này tính tổng của mỗi hàng (sum(row)) và sử dụng nó làm tiêu chí sắp xếp.

* Kết quả là một ma trận mới (sorted_matrix) chứa các hàng đã được sắp xếp theo tổng hàng.

* Sau đó, hàm sort_by_row_sum được gọi để sắp xếp ma trận matrix đã được định nghĩa trước đó. Kết quả được lưu vào biến sorted_matrix, và mỗi hàng của ma trận đã sắp xếp được in ra dưới dạng các dòng riêng biệt.

In [5]:
# Cách 2
def sort_by_row_sum(matrix):
    # Sắp xếp các hàng trong ma trận theo tổng của từng hàng
    sorted_matrix = sorted(matrix, key=lambda row: sum(row))
    
    return sorted_matrix

# Kiểm tra
matrix = [
    [4, 2, 7],
    [1, 5, 6],
    [3, 8, 2]
]

# Gọi hàm sort_by_row_sum để sắp xếp ma trận theo tổng hàng
sorted_matrix = sort_by_row_sum(matrix)

# In ra từng hàng trong ma trận đã sắp xếp
for row in sorted_matrix:
    print(row)


[1, 5, 6]
[4, 2, 7]
[3, 8, 2]


## Bài tập 3: Quản lý hàng tồn kho (advanced)

Một công ty có một danh sách hàng tồn kho của các sản phẩm khác nhau. Các thông tin hàng tồn kho bao gồm tên sản phẩm, số lượng trong kho, và giá bán của mỗi sản phẩm. Công ty muốn tính toán tổng giá trị của hàng tồn kho của mình.

Danh sách hàng tồn kho của công ty được biểu diễn bằng một ma trận có kích thước nx3, trong đó n là số lượng sản phẩm khác nhau. Các cột trong ma trận biểu diễn tên sản phẩm, số lượng trong kho và giá bán của mỗi sản phẩm.

Ví dụ, ma trận hàng tồn kho có thể nhìn như sau:

Hàng tồn kho:
```
|    Tên    | Số lượng | Giá bán |
|  Sản phẩm 1 |    10    |   5.0   |
|  Sản phẩm 2 |    5     |   2.5   |
|  Sản phẩm 3 |    3     |   8.0   |
```

Tính tổng số lượng hàng tồn kho của tất cả các sản phẩm.

Tính giá trị hàng tồn kho của mỗi sản phẩm bằng cách nhân số lượng với giá bán của sản phẩm tương ứng.

Tính tổng giá trị của toàn bộ hàng tồn kho.

Hãy viết các phương trình hoặc mã code để giải quyết từng bài tập trên.


In [12]:
# Ma trận hàng tồn kho
inventory = [
    ["Sản phẩm 1", 10, 5.0],
    ["Sản phẩm 2", 5, 2.5],
    ["Sản phẩm 3", 3, 8.0]
]

# Tính tổng số lượng hàng tồn kho của tất cả các sản phẩm
total_quantity = sum(item[1] for item in inventory)
print("Tổng số lượng hàng tồn kho:", total_quantity)

# Tính giá trị hàng tồn kho của mỗi sản phẩm
product_values = [item[1] * item[2] for item in inventory]
print("Giá trị hàng tồn kho của mỗi sản phẩm:", product_values)

# Tính tổng giá trị của toàn bộ hàng tồn kho
total_value = sum(product_values)
print("Tổng giá trị hàng tồn kho:", total_value)


Tổng số lượng hàng tồn kho: 18
Giá trị hàng tồn kho của mỗi sản phẩm: [50.0, 12.5, 24.0]
Tổng giá trị hàng tồn kho: 86.5


# Phần 2: List 3D

## Bài tập 1: Viết hàm find_max để tìm giá trị lớn nhất trong một list 3D. List 3D có thể được biểu diễn như sau:
```
list_3d = [
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
]

```

```mermaid
graph TB
  A[Start]
  B[Set max_value as first element of list]
  C[Iterate over 3D list]
  D{Check if current value > max_value}
  E[Set max_value as current value]
  F[End]
  G[Continue]
  
  A --> B
  B --> C
  C --> D
  D -- Yes --> E
  E --> C
  D -- No --> G
  G --> C
  C -- End of list --> F

```

Các bước thực hiện:

* Khởi tạo biến max_value với giá trị ban đầu là phần tử đầu tiên của danh sách 3D (list_3d[0][0][0]).

* Sử dụng các vòng lặp để duyệt qua các phần tử trong danh sách 3D. Đầu tiên, vòng lặp for đầu tiên duyệt qua các danh sách 2D (list_2d) trong danh sách 3D (list_3d).

* Trong vòng lặp for thứ hai, duyệt qua các danh sách 1D (list_1d) trong danh sách 2D hiện tại.

* Trong vòng lặp for thứ ba, duyệt qua từng giá trị (value) trong danh sách 1D hiện tại.

* Tại mỗi vòng lặp, so sánh giá trị hiện tại với giá trị lớn nhất hiện tại (max_value). Nếu giá trị hiện tại lớn hơn, cập nhật giá trị lớn nhất (max_value).

* Sau khi hoàn thành các vòng lặp, trả về giá trị lớn nhất tìm được (max_value).

Sau đó, hàm find_max được gọi để tìm giá trị lớn nhất trong danh sách 3D list_3d đã được định

In [4]:
def find_max(list_3d):
    # Khởi tạo giá trị lớn nhất với giá trị đầu tiên của list_3d
    max_value = list_3d[0][0][0]
    
    # Duyệt qua các list 2D trong list 3D
    for list_2d in list_3d:
        # Duyệt qua các list 1D trong list 2D
        for list_1d in list_2d:
            # Duyệt qua các giá trị trong list 1D
            for value in list_1d:
                # So sánh giá trị hiện tại với giá trị lớn nhất hiện tại
                if value > max_value:
                    # Nếu giá trị hiện tại lớn hơn, cập nhật giá trị lớn nhất
                    max_value = value
    
    return max_value

list_3d = [
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
]

print(find_max(list_3d))  # Output: 12


12


## Bài tập 2: Viết hàm flatten_3d_list để làm phẳng một list 3D thành một list 1D (danh sách một chiều). Sử dụng cùng list 3D trong bài tập 1, hàm flatten_3d_list nên trả về:

```
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

```
Lưu ý: Hãy cố gắng sử dụng nested for loops (vòng lặp for lồng nhau) hoặc list comprehension để giải quyết các bài tập này.

```mermaid
graph TB
  A[Start]
  B[Initialize empty flattened_list]
  C[Iterate over 3D list]
  D[Append current value to flattened_list]
  E[End]
  
  A --> B
  B --> C
  C --> D
  D --> C
  C -- End of list --> E

```

Các bước thực hiện:

* Khởi tạo một danh sách mới (flattened_list) để lưu các giá trị đã được làm phẳng.

* Sử dụng các vòng lặp để duyệt qua các phần tử trong danh sách 3D. Đầu tiên, vòng lặp for đầu tiên duyệt qua các danh sách 2D (list_2d) trong danh sách 3D (list_3d).

* Trong vòng lặp for thứ hai, duyệt qua các danh sách 1D (list_1d) trong danh sách 2D hiện tại.

* Trong vòng lặp for thứ ba, duyệt qua từng giá trị (value) trong danh sách 1D hiện tại.

* Tại mỗi vòng lặp, thêm giá trị vào danh sách đã làm phẳng (flattened_list) bằng cách sử dụng phương thức append.

* Sau khi hoàn thành các vòng lặp, trả về danh sách đã làm phẳng (flattened_list).

Sau đó, hàm flatten_3d_list được gọi để làm phẳng danh sách 3D list_3d đã được định nghĩa trước đó. Kết quả được in ra màn hình. 

In [8]:
def flatten_3d_list(list_3d):
    # Khởi tạo danh sách mới để lưu các giá trị đã được làm phẳng
    flattened_list = []
    
    # Duyệt qua các danh sách 2D trong danh sách 3D
    for list_2d in list_3d:
        # Duyệt qua các danh sách 1D trong danh sách 2D
        for list_1d in list_2d:
            # Duyệt qua từng giá trị trong danh sách 1D
            for value in list_1d:
                # Thêm giá trị vào danh sách đã làm phẳng
                flattened_list.append(value)
    
    return flattened_list

list_3d = [
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
]

print(flatten_3d_list(list_3d))  # Output: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


## (Advanced) Bài tập 3: Xoay list 3D theo chiều kim đồng hồ
Hãy viết một hàm rotate_3d_clockwise nhận vào một list 3D và trả về list 3D đã được xoay 90 độ theo chiều kim đồng hồ. Giả sử rằng kích thước của các list con luôn đồng nhất.

Ví dụ: 
```
input:
list_3d = [
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
]

output:
[
    [[[7, 8, 9], [1, 2, 3]],
     [[10, 11, 12], [4, 5, 6]]]
]

```
```mermaid
graph TB
  A[Start]
  B[Iterate over and unzip 3D list]
  C[Reverse each unzipped list]
  D[Return rotated 3D list]
  E[End]

  A --> B
  B --> C
  C --> D
  D --> E
```


Các bước thực hiện:

* Sử dụng zip(*list_3d) để tạo ra các tuple chứa phần tử tương ứng từ các list con trong list_3d. Kết quả là một danh sách mới, trong đó mỗi phần tử là một tuple chứa các phần tử tương ứng từ các list con.

* Sử dụng reversed để đảo ngược thứ tự các phần tử trong mỗi tuple.

* Sử dụng list để chuyển đổi mỗi tuple đã đảo ngược thành một list.

* Kết quả là một danh sách mới, trong đó mỗi phần tử là một list con đã được quay theo chiều kim đồng hồ.

Hàm trả về danh sách đã quay. Sau đó, hàm rotate_3d_clockwise được gọi để quay ma trận 3D list_3d đã được định nghĩa trước đó. Kết quả được in ra màn hình.

In [5]:
def rotate_3d_clockwise(list_3d):
    # Sử dụng zip và reversed để quay ma trận 3D theo chiều kim đồng hồ
    # list(reversed(x)) sẽ tạo ra một bản sao của mỗi list con trong list_3d và đảo ngược thứ tự các phần tử trong mỗi list con.
    # zip(*list_3d) sẽ tạo ra các tuple chứa phần tử tương ứng từ các list con trong list_3d.
    # Kết quả là một danh sách mới mà mỗi phần tử là một list đã được quay theo chiều kim đồng hồ.
    return [list(reversed(x)) for x in zip(*list_3d)]

list_3d = [
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
]

print(rotate_3d_clockwise(list_3d))


[[[7, 8, 9], [1, 2, 3]], [[10, 11, 12], [4, 5, 6]]]


# Phần 3 Numpy

## 1D array Basic

### 1. Bạn hãy tạo 1D array gồm 5 phần tử [1, 2, 3, 4, 5]. Sau đó in ra màn hình 1D array vừa tạo ?

In [15]:
import numpy as np

# Tạo mảng 1D
array_1d = np.array([1, 2, 3, 4, 5])

# In mảng
print(array_1d)


[1 2 3 4 5]


### 2. Bạn hãy xây dựng chương trình thực hiện tính tổng các phần tử trong 1D array?
Input: my_arr = [1, 2, 3, 4, 5]
Output: 15


Để tính tổng các phần tử trong một mảng 1 chiều, bạn có thể sử dụng hàm `np.sum()`

In [16]:
import numpy as np

# Tạo mảng 1D
my_arr = np.array([1, 2, 3, 4, 5])

# Tính tổng các phần tử trong mảng
sum_of_elements = np.sum(my_arr)

# In kết quả
print(sum_of_elements)


15


### 3. Bạn hãy xây dựng chương trình tìm giá trị lớn nhất và nhỏ nhất trong 1d array?
Input: my_arr = [1, 2, 3, 4, 5]

Output: max = 5, min = 1

Gợi ý: Để tìm giá trị lớn nhất và nhỏ nhất trong một mảng 1 chiều, bạn có thể sử dụng hai hàm là np.max() và np.min().

In [17]:
import numpy as np

# Tạo mảng 1D
my_arr = np.array([1, 2, 3, 4, 5])

# Tìm giá trị lớn nhất
max_value = np.max(my_arr)

# Tìm giá trị nhỏ nhất
min_value = np.min(my_arr)

# In kết quả
print("max =", max_value)
print("min =", min_value)


max = 5
min = 1


### 4. Bạn hãy xây dựng chương trình tính trung bình cộng của 1D array?
Input: my_array = [1, 2, 3, 4, 5]
Output: 3.0

Gợi ý: Để tính trung bình cộng của các phần tử trong một mảng 1 chiều, bạn có thể sử dụng hàm `np.mean()`

In [18]:
import numpy as np

# Tạo mảng 1D
my_array = np.array([1, 2, 3, 4, 5])

# Tính trung bình cộng
mean_value = np.mean(my_array)

# In kết quả
print(mean_value)


3.0


### 5. Bạn hãy xây dựng chương trình sắp xếp 1D array sau theo chiều tăng dần hoặc giảm dần?
Input: my_array = [5, 3, 1, 4, 2]
Output: tăng dần [1, 2, 3, 4, 5], giảm dần: [5, 4, 3, 2, 1]

Gợi ý: Để sắp xếp một mảng 1 chiều, bạn có thể sử dụng hàm np.sort(). Để sắp xếp theo chiều giảm dần, bạn có thể sử dụng cú pháp slicing để đảo ngược mảng đã sắp xếp tăng dần.

In [6]:
import numpy as np

# Tạo mảng 1D
my_array = np.array([5, 3, 1, 4, 2])

# Sắp xếp tăng dần
ascending = np.sort(my_array)

# Sắp xếp giảm dần
descending = ascending[::-1]

# In kết quả
print("tăng dần:", ascending)
print("giảm dần:", descending)


tăng dần: [1 2 3 4 5]
giảm dần: [5 4 3 2 1]


### 6. Bạn hãy xây dựng chương trình tổng các phần tử trên các vị trí chẵn hoặc lẻ?
Input: my_array = [1, 2, 3, 4, 5]
Output: even = 6, odd =9

Gợi ý: Để tính tổng các phần tử ở vị trí chẵn hoặc lẻ trong mảng, bạn có thể sử dụng slicing trong Numpy

In [20]:
import numpy as np

# Tạo mảng 1D
my_array = np.array([1, 2, 3, 4, 5])

# Tính tổng các phần tử ở vị trí chẵn (0-based index)
even_sum = np.sum(my_array[::2])

# Tính tổng các phần tử ở vị trí lẻ
odd_sum = np.sum(my_array[1::2])

# In kết quả
print("even =", even_sum)
print("odd =", odd_sum)


even = 9
odd = 6


## 1D array Advance

### 1. Bạn hãy xây dựng chương trình tìm các số chẵn trong array và tính tổng của chúng ?
Input: my_array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Output: even_numbers = [2, 4, 6, 8, 10], sum_even = 30

Gợi ý: 
Để thực hiện điều này, bạn có thể sử dụng Boolean Indexing trong Numpy để lọc ra các số chẵn và sau đó tính tổng của chúng

In [21]:
import numpy as np

# Tạo mảng 1D
my_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Lọc ra các số chẵn
even_numbers = my_array[my_array % 2 == 0]

# Tính tổng các số chẵn
sum_even = np.sum(even_numbers)

# In kết quả
print("even_numbers =", even_numbers)
print("sum_even =", sum_even)


even_numbers = [ 2  4  6  8 10]
sum_even = 30


### 2.  Bạn hãy xây dựng chương trình tính tổng của các số nguyên tố trong array?
Input: my_array = [2, 3, 4, 5, 6, 7, 8, 9, 10]

Output: prime_numbers = [2, 3, 5, 7], sum_prime = 17

Để giải bài toán này, trước hết chúng ta cần định nghĩa hàm để kiểm tra một số có phải là số nguyên tố hay không. Sau đó, chúng ta sẽ sử dụng hàm này để lọc ra các số nguyên tố từ mảng và tính tổng của chúng.

Các bước thực hiện:

* Hàm is_prime để kiểm tra xem một số n có phải là số nguyên tố hay không. Mô tả chức năng của hàm đã được cung cấp trong docstring.

* Tạo một mảng 1D (my_array) bằng cách sử dụng np.array và cung cấp các giá trị.

* Sử dụng hàm np.vectorize kết hợp với is_prime để áp dụng kiểm tra số nguyên tố lên từng phần tử của my_array. Kết quả là một mảng Boolean, trong đó giá trị True tương ứng với số nguyên tố và False tương ứng với số không phải là số nguyên tố.

* Sử dụng mảng Boolean trên (prime_numbers) làm chỉ mục để lọc ra các số nguyên tố từ my_array.

* Sử dụng np.sum để tính tổng các số nguyên tố trong prime_numbers.

Sử dụng print để in kết quả, bao gồm mảng các số nguyên tố (prime_numbers) và tổng các số nguyên tố (sum_prime).

In [22]:
import numpy as np

def is_prime(n):
    """Kiểm tra n có phải là số nguyên tố không"""
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Tạo mảng 1D
my_array = np.array([2, 3, 4, 5, 6, 7, 8, 9, 10])

# Lọc ra các số nguyên tố
prime_numbers = my_array[np.vectorize(is_prime)(my_array)]

# Tính tổng các số nguyên tố
sum_prime = np.sum(prime_numbers)

# In kết quả
print("prime_numbers =", prime_numbers)
print("sum_prime =", sum_prime)


prime_numbers = [2 3 5 7]
sum_prime = 17


### 3. Bạn hãy xây dựng chương trình tính tổng các số dương và tích các số âm trong array?
Input: my_array = [-1, 2, -3, 4, -5, 6]

Output:  sum_positive = 12, product_negative = -15

Để tính tổng các số dương và tích các số âm trong mảng, bạn có thể sử dụng Boolean Indexing trong Numpy để lọc ra các số dương và số âm, sau đó tính tổng và tích tương ứng.

In [23]:
import numpy as np

# Tạo mảng 1D
my_array = np.array([-1, 2, -3, 4, -5, 6])

# Lọc ra các số dương
positive_numbers = my_array[my_array > 0]

# Tính tổng các số dương
sum_positive = np.sum(positive_numbers)

# Lọc ra các số âm
negative_numbers = my_array[my_array < 0]

# Tính tích các số âm
product_negative = np.product(negative_numbers)

# In kết quả
print("sum_positive =", sum_positive)
print("product_negative =", product_negative)


sum_positive = 12
product_negative = -15


### 4. Bạn hãy xây dựng chương trình tính tổng các số trong array sau khi loại bỏ các số trùng lặp?
Input: my_array = [1, 2, 3, 2, 4, 5, 1, 6, 7, 8, 5]
Output: unique_numbers = [1, 2, 3, 4, 5, 6, 7, 8], sum_unique =36

In [24]:
import numpy as np

# Tạo mảng 1D
my_array = np.array([1, 2, 3, 2, 4, 5, 1, 6, 7, 8, 5])

# Loại bỏ các số trùng lặp
unique_numbers = np.unique(my_array)

# Tính tổng các số duy nhất
sum_unique = np.sum(unique_numbers)

# In kết quả
print("unique_numbers =", unique_numbers)
print("sum_unique =", sum_unique)


unique_numbers = [1 2 3 4 5 6 7 8]
sum_unique = 36


## 2D array basic

1. Bạn hãy xây dựng chương trình tính tổng các phần tử trong array 2D?

Input: my_array = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Output: total = 45

Gợi ý: 
Để tính tổng các phần tử trong một mảng 2D, bạn có thể sử dụng hàm np.sum()

In [25]:
import numpy as np

# Tạo mảng 2D
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Tính tổng các phần tử
total = np.sum(my_array)

# In kết quả
print("total =", total)


total = 45


### 2. Bạn hãy xây dựng chương trình tìm giá trị lớn nhất và nhỏ nhất trong 2D array?
Input: my_array = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Output: max_value = 9, min_value = 1

In [26]:
import numpy as np

# Tạo mảng 2D
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Tìm giá trị lớn nhất
max_value = np.max(my_array)

# Tìm giá trị nhỏ nhất
min_value = np.min(my_array)

# In kết quả
print("max_value =", max_value)
print("min_value =", min_value)


max_value = 9
min_value = 1


### 3. Bạn hãy xây dựng chương trình tính trung bình cộng của 2D array?

Input: my_array = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Output: average = 5.0

In [27]:
import numpy as np

# Tạo mảng 2D
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Tính trung bình cộng
average = np.mean(my_array)

# In kết quả
print("average =", average)


average = 5.0


### 4. Bạn hãy xây dựng chương trình sắp xếp danh sách 2D theo thứ tự tăng dần hoặc giảm dần?

Input: my_list = [[5, 3, 1], [4, 2, 6], [9, 7, 8]]

Output: sorted_list = [[1, 3, 5], [2, 4, 6], [7, 8, 9]], 
reverse_sorted_list = [[5, 3, 1], [6, 4, 2], [9, 8, 7]]

Gợi ý: Để sắp xếp mảng 2D theo thứ tự tăng dần hoặc giảm dần, bạn có thể sử dụng hàm np.sort(). Tuy nhiên, cần chú ý rằng hàm này sắp xếp các hàng riêng lẻ, chứ không sắp xếp toàn bộ mảng như một đơn vị

In [28]:
import numpy as np

# Tạo mảng 2D
my_array = np.array([[5, 3, 1], [4, 2, 6], [9, 7, 8]])

# Sắp xếp mảng tăng dần
sorted_array = np.sort(my_array, axis=1)

# Sắp xếp mảng giảm dần
reverse_sorted_array = -np.sort(-my_array, axis=1)

# In kết quả
print("sorted_array =\n", sorted_array)
print("reverse_sorted_array =\n", reverse_sorted_array)


sorted_array =
 [[1 3 5]
 [2 4 6]
 [7 8 9]]
reverse_sorted_array =
 [[5 3 1]
 [6 4 2]
 [9 8 7]]


## 2D Advanced

### 1. Bạn hãy xây dựng chương trình tính tổng các phần tử trong mỗi hàng và tính tổng của các tổng hàng?

Input: my_array = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Output: row_sums= [6, 15, 24], total_sum = 45

Gợi ý: 
Để tính tổng các phần tử trong mỗi hàng và tổng của các tổng hàng trong một mảng 2D, bạn có thể sử dụng hàm np.sum()

In [33]:
import numpy as np

# Tạo mảng 2D
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Tính tổng các phần tử trong mỗi hàng
row_sums = np.sum(my_array, axis=1)

# Tính tổng của các tổng hàng
total_sum = np.sum(row_sums)

# In kết quả
print("row_sums =", row_sums)
print("total_sum =", total_sum)


row_sums = [ 6 15 24]
total_sum = 45


### 2. Bạn hãy xây dựng chương trình tính tổng các phần tử trong mỗi cột và tính tổng của các tổng cột?
Input: my_array = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Output: column_sums = [12, 15, 18], total_sum = 45

gợi: Để tính tổng các phần tử trong mỗi cột và tổng của các tổng cột trong một mảng 2D, bạn có thể sử dụng hàm np.sum()

In [34]:
import numpy as np

# Tạo mảng 2D
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Tính tổng các phần tử trong mỗi cột
column_sums = np.sum(my_array, axis=0)

# Tính tổng của các tổng cột
total_sum = np.sum(column_sums)

# In kết quả
print("column_sums =", column_sums)
print("total_sum =", total_sum)


column_sums = [12 15 18]
total_sum = 45


### 3. Bạn hãy xây dựng chương trình tìm phần tử lớn nhất và vị trí của phần tử đó trong 2D array?
Input: my_array = [[1, 2, 3], [4, 9, 6], [7, 8, 5]]

Output: max_value = 9; max_row, max_col = 1, 1

Gợi ý: 
Để tìm phần tử lớn nhất và vị trí của phần tử đó trong một mảng 2D, bạn có thể sử dụng hàm np.max() để tìm phần tử lớn nhất và np.unravel_index() để tìm vị trí

In [35]:
import numpy as np

# Tạo mảng 2D
my_array = np.array([[1, 2, 3], [4, 9, 6], [7, 8, 5]])

# Tìm phần tử lớn nhất
max_value = np.max(my_array)

# Tìm vị trí của phần tử lớn nhất
max_position = np.unravel_index(np.argmax(my_array), my_array.shape)

# In kết quả
print("max_value =", max_value)
print("max_row, max_col =", max_position)


max_value = 9
max_row, max_col = (1, 1)
